apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sentry
  namespace: default
  labels:
    app: sentry
spec:
  selector:
    matchLabels:
      app: sentry
  template:
    metadata:
      labels:
        app: sentry
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9091"
        prometheus.io/path: "/metrics"
    spec:
      hostNetwork: true
      hostPID: true
      containers:
        - name: sentry
          image: sentry:v6
          imagePullPolicy: Never
          env:
            - name: RUST_LOG
              value: info
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
                - NET_ADMIN
          volumeMounts:
            - name: bpf-fs
              mountPath: /sys/fs/bpf
              mountPropagation: Bidirectional
            - name: debug-fs
              mountPath: /sys/kernel/debug
              mountPropagation: Bidirectional
      volumes:
        - name: bpf-fs
          hostPath:
            path: /sys/fs/bpf
            type: Directory
        - name: debug-fs
          hostPath:
            path: /sys/kernel/debug
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: sentry
  namespace: default
  labels:
    app: sentry
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9091"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: sentry
  ports:
    - name: metrics
      port: 9091
      targetPort: 9091
      protocol: TCP
  clusterIP: None # Headless service, we want individual pod IPs
