apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
# --- 1. TEMPO (The Trace Store) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:latest
          args: ["-config.file=/etc/tempo.yaml"]
          ports:
            - containerPort: 4317 # OTLP gRPC (Rust sends data here)
            - containerPort: 3200 # HTTP (Grafana reads data here)
          volumeMounts:
            - name: tempo-conf
              mountPath: /etc/tempo.yaml
              subPath: tempo.yaml
      volumes:
        - name: tempo-conf
          configMap:
            name: tempo-conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-conf
  namespace: monitoring
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200
    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: "0.0.0.0:4317"
    ingester:
      trace_idle_period: 10s
      max_block_bytes: 1_000_000
      max_block_duration: 5m
    compactor:
      compaction:
        compaction_window: 1h
    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/blocks
        wal:
          path: /tmp/tempo/wal
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: monitoring # Note: We need a Service in 'default' too for cross-namespace talk
spec:
  selector:
    app: tempo
  ports:
    - name: grpc
      port: 4317
      targetPort: 4317
    - name: http
      port: 3200
      targetPort: 3200
---
# --- 2. GRAFANA (The Dashboard) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Admin"
          volumeMounts:
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
              subPath: datasources.yaml
      volumes:
        - name: datasources
          configMap:
            name: grafana-datasources
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Tempo
      type: tempo
      access: proxy
      orgId: 1
      url: http://tempo.monitoring.svc.cluster.local:3200
      basicAuth: false
      isDefault: true
      version: 1
      editable: false
      apiVersion: 1
      uid: tempo
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector:
    app: grafana
  ports:
    - port: 80
      targetPort: 3000
---
# --- 3. BRIDGE (Allow Default Namespace to Talk to Monitoring) ---
# Your Rust app is in 'default', Tempo is in 'monitoring'
# This Service makes "http://tempo:4317" work in 'default'
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: default
spec:
  type: ExternalName
  externalName: tempo.monitoring.svc.cluster.local
  ports:
    - port: 4317
