apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
# ==========================================
# 1. PROMETHEUS SERVER (The Metrics Database)
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-server-conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s 
      evaluation_interval: 5s

    scrape_configs:
      # Scrape the Kube-Cache Operator (Your Rust App in default ns)
      - job_name: 'kube-cache'
        static_configs:
          - targets: ['kube-cache.default.svc.cluster.local:8080']
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: monitoring
spec:
  selector:
    app: prometheus-server
  ports:
    - port: 80
      targetPort: 9090
---
# ==========================================
# 2. TEMPO (The Trace Store)
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:latest
          args: ["-config.file=/etc/tempo.yaml"]
          ports:
            - containerPort: 4317 # OTLP gRPC
            - containerPort: 3200 # HTTP
          volumeMounts:
            - name: tempo-conf
              mountPath: /etc/tempo.yaml
              subPath: tempo.yaml
      volumes:
        - name: tempo-conf
          configMap:
            name: tempo-conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-conf
  namespace: monitoring
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200
    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: "0.0.0.0:4317"
    ingester:
      trace_idle_period: 10s
      max_block_bytes: 1_000_000
      max_block_duration: 5m
    compactor:
      compaction:
        compaction_window: 1h
    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/blocks
        wal:
          path: /tmp/tempo/wal
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: monitoring
spec:
  selector:
    app: tempo
  ports:
    - name: grpc
      port: 4317
      targetPort: 4317
    - name: http
      port: 3200
      targetPort: 3200
---
# ==========================================
# 3. GRAFANA (The Dashboard) -- UPDATED
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Admin"
          volumeMounts:
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
              subPath: datasources.yaml
      volumes:
        - name: datasources
          configMap:
            name: grafana-datasources
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    # ADDED PROMETHEUS HERE
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-server.monitoring.svc.cluster.local:80
      isDefault: true
    # TEMPO REMAINS
    - name: Tempo
      type: tempo
      access: proxy
      url: http://tempo.monitoring.svc.cluster.local:3200
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector:
    app: grafana
  ports:
    - port: 80
      targetPort: 3000
---
# ==========================================
# 4. BRIDGES & SERVICES
# ==========================================
# Allow 'default' namespace to talk to 'monitoring' namespace (Tempo)
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: default
spec:
  type: ExternalName
  externalName: tempo.monitoring.svc.cluster.local
  ports:
    - port: 4317
---
# Expose the Rust App so Prometheus can scrape it
apiVersion: v1
kind: Service
metadata:
  name: kube-cache
  namespace: default
spec:
  selector:
    app: kube-cache
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
