apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-1
  annotations:
    "x-openai/required-dataset": "s3://models/gpt-4-weights"
spec:
  schedulingGates:
    - name: "kube-cache.openai.com/gate"
  containers:
    - name: cuda-container
      image: nvidia/cuda:11.0-base
      command: ["sh", "-c", "echo 'Training...'; sleep 30"]
